[build]
  command = "go build -o main"
  publish = "."

[functions]
  [functions.name]
    name = "golang"
    memory = 128
    timeout = 10
    runtime = "go1.19"
    environment = { GO_ENV = "production" }
    command = "main"
    path = "golang"