[build]
  command = "go build -o ./functions/golang main.go"
  publish = "public"

[functions]
  name = "golang"
  memory = 128
  timeout = 10
  runtime = "go1.19"
  environment = { GO_ENV = "production" }
  command = "./golang"
  path = "functions/golang"